name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-dev build-essential git zlib1g-dev openjdk-17-jdk
        python3 -m pip install --upgrade pip

    - name: Install Buildozer & Cython
      run: |
        pip install --upgrade buildozer cython==0.30.1

    - name: Build APK
      run: buildozer android debug
